events {}

http {
    server {
        listen              4000 ssl;
        ssl_certificate     /app/ssl/server.crt;
        ssl_certificate_key /app/ssl/server.key;

        location / {
            proxy_pass       http://127.0.0.1:2300;
            port_in_redirect off;
        }
    }
}
