events {}

http {
    server {
        listen              4000 ssl;
        ssl_certificate     /app/ssl/server.crt;
        ssl_certificate_key /app/ssl/server.key;

        # Allow larger request bodies than nginx's 1m default (e.g. file uploads)
        client_max_body_size 50m;

        location / {
            proxy_pass       http://127.0.0.1:2300;
            proxy_set_header Host $host;
            port_in_redirect off;

            # Upstream can write larger response headers than nginx's extremely conservative defaults
            proxy_buffer_size       16k;   # default: 4k|8k (one memory page)
            proxy_buffers           4 16k; # default: 8 4k|8k
            proxy_busy_buffers_size 16k;   # default: 8k|16k (two memory pages)
        }
    }
}
