image: public.ecr.aws/perx/node16-builder:latest

definitions:
  services:
    docker:
      memory: 2048
  steps:
    - step: &Node14
        name: Build and push -> Node 14
        services:
          - docker
        script:
          - export AWS_ACCESS_KEY_ID=$MGMT_AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$MGMT_AWS_SECRET_ACCESS_KEY
          - export DOCKERFILE_PATH="node/node14-builder"
          - export IMAGE_VERSION="${BITBUCKET_COMMIT::6}"
          - export IMAGE_NAME="node14-builder"
          - ci/scripts/login-to-ecr.sh
          - ci/scripts/build-and-push.sh

pipelines:
  pull-requests:
    '**':
      - parallel:
        - step: *Node14
