image: public.ecr.aws/perx/aws:latest

definitions:
  services:
    docker:
      memory: 2048
  steps:
    - step: &Node14
        name: Build and push -> Node 14
        services:
          - docker
        script:
          - export AWS_ACCESS_KEY_ID=$MGMT_AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$MGMT_AWS_SECRET_ACCESS_KEY
          - export AWS_ACCOUNT_ID=651180711168
          - export AWS_ROLE=perx-mgmt-admin
          - export HEAD_SHA="${BITBUCKET_COMMIT::6}"
          - source ci/scripts/assume-role.sh
          - cd node/node14-builder
          - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/perx
          - docker build -t node14-builder:$HEAD_SHA -f Dockerfile .
          - docker tag node14-builder:$HEAD_SHA public.ecr.aws/perx/node14-builder:$HEAD_SHA
          - docker push public.ecr.aws/perx/node14-builder:$HEAD_SHA

pipelines:
  pull-requests:
    '**':
      - parallel:
        - step: *Node14
